---
# tasks file for Roles/php7
- name: setting repository 
  yum :
    name:  
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - epel-release 
    - yum-utils
    state: present
- name: activation of php7 repository
  command:  yum-config-manager --enable remi-php73    
- name: installation of php7
  yum:
    name:
    - php 
    - php-common 
    - php-opcache 
    - php-mcrypt 
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd
    state: present