---
- name: Install required packages
  package:
    name:
      - git
      - gcc
      - gcc-c++
      - nodejs
      - npm
      - gettext
      - python3-pip
      - python3-wheel
      - libffi-devel
      - openssl-devel
      - git
    state: present

- name: Ajouter la clé du référentiel RPM
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Installer le référentiel Docker CE
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/{{ansible_distribution_major_version}}/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present

- name: Installer Dockerp
  yum:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present

- name: Démarrer et activer Docker
  systemd:
    name: docker
    enabled: true
    state: started

# - name: Installer Docker Compose
#   shell:
#   |
#     'curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
#     sudo chmod +x /usr/local/bin/docker-compose
    
# - name: Install Docker Compose
#   pip:
#     name: docker-compose
#     version: "{{ docker_compose_version }}"
#     state: present

# - name: Wait for containers to start
#   wait_for:
#     host: localhost
#     port: 80
#     delay: 5
