---
- name: installation of nginx
  yum:
    name: nginx,curl
    state: present 
- name: start service and activit
  service:
    name: nginx
    state: started
    enabled: yes 
     
- name: Create a directory available and enabled  if it does not exist
  file:
   path : "{{ item }}"
   state: directory
   mode: '0755'
  with_items:
  - "/etc/nginx/sites-available"
  - "/etc/nginx/sites-enabled"

- name: copy vhost file to default
  template:
    src: default_vhost.conf.js2
    dest: /etc/nginx/sites-available/host1.conf
    owner: root 
    group: nginx 
  notify: add modification in hosts file 

- name: create the symbol link
  file:
   src: /etc/nginx/sites-available/host1.conf 
   dest:  /etc/nginx/sites-enabled/host1.conf
   state: link 
  notify: restart service after upload new vhost
   
- name: copy file to server
  copy:
    src: ../files/store/
    dest: /usr/share/nginx/html/

