#### installation of nginx php7 and nginx_loadbalance
- name: create  ssh_keyg on localhost
  connection: local
  hosts: localhost
  roles: 
  - ssh_key

- name: create user to connect on remode server with ssh_keyg
  hosts: client
  become: yes
  roles:
  - user
  - php7
# - nginx
#  - mysql
 #  - nginx_load_ba
 
- name: create kubenete on remode server with node
  hosts: ser_all
  become: yes
  roles:
  - docker
  - Kubernet
  - user