---
- hosts: client
  become: yes
  tasks:
    - name: setting repository 
      yum :
       name:  
       - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
       - epel-release 
       - yum-utils
       state: present
    - name: activation of php7 repository
      shell:
           |
            yum-config-manager --enable remi-php73
            yum list all 
            yum install php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysqlnd
    - name: installation of nginx
      yum:
       name:
        - nginx
       state: present
    - name: start service and activit
      service:
        name: nginx
        state: started
        enabled: yes    
    - name: copy file to server
      copy:
       src: ../store/
       dest: /usr/share/nginx/html/
      