---
- hosts: client
  become: yes
  tasks:
    - name: setting repository 
      yum :
       name:  
       - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
       - epel-release 
       - yum-utils
       state: present
    - name: activation of php7 repository
      shell:
           |
            yum-config-manager --enable remi-php73    
    - name: installation of nginx
      yum:
       name:
        - nginx
        - php 
        - php-common 
        - php-opcache 
        - php-mcrypt 
        - php-cli
        - php-gd
        - php-curl
        - php-mysqlnd
       state: present
    - name: start service and activit
      service:
        name: nginx
        state: started
        enabled: yes    
    - name: copy file to server
      copy:
       src: ../store/
       dest: /usr/share/nginx/html/

    - name: change values 
      lineinfile:
       path: /etc/php.ini
       regexp: ^display_errors = Off
       line:  'display_errors = On'

      