---
- hosts: client
  become: yes
  tasks:
    - name: permit traffic in default zone for https service
      firewalld:
       service: https
       permanent: true
       state: enabled
    - name:
      template:
       src: ../templates/laodbalance.js2
       dest: /etc/nginx/conf.d/ldng.conf
       mode: 654
      notify: restart nginx
    
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restart
         