---
- hosts: client
  become: yes
  tasks:
    - name: disable service 
      service:
       name: nginx
       state: stopped
    - name: remove nginx
      yum:
       name: nginx
       state: absent
