---
- hosts: client
  become: yes
  vars:
   desrr: "/var/www"
   desrt: /opt/dr/
  tasks:
    - name: collect hostname of hosts to file info
      copy:
       dest: "{{ desrr }}/info"
       content: "{{ ansible_hostname}}"
       force: true
    - name: create folder
      file:
       dest: "{{desrt}}"
       state: directory
       force: yes
    - name: create multiple folder
      shell: |
             mkdir -p /opt/dr/file{2,3,4,6,7,9}
    - name: send html information
      copy:
        dest: "{{desrt}}/info.html"
        content: "hello this is <h1>hello, Wolrld!</h1>"
        force: yes
